# Generated by Django 3.1.4 on 2021-01-06 02:44

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload_work_files',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files', validators=[authentication.validators.validate_file_extension]),
        ),
    ]
