# Generated by Django 3.1.4 on 2021-01-06 03:32

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210106_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='user',
            name='upload_work_files',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
    ]
