# Generated by Django 3.1 on 2021-03-07 20:35

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210302_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload_work_files_eight',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_eleven',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_five',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_four',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_nine',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_one',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_seven',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_six',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_ten',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_three',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_twelve',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_work_files_two',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_file_extension]),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
