# Generated by Django 3.1.4 on 2021-01-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210106_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_type',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'Arabic')], default=2),
        ),
    ]
