# Generated by Django 3.1.4 on 2021-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210109_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_pro',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=b'', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_pro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_description_pro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_title_pro',
            field=models.CharField(default='', max_length=255),
        ),
    ]
