# Generated by Django 3.1.4 on 2021-01-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210109_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='about_me',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='job_pro',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skills_pro',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='work_description_pro',
            new_name='work_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='work_title_pro',
            new_name='work_title',
        ),
    ]
