# Generated by Django 3.1.4 on 2021-01-09 13:24

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210109_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='uploaded_files/', validators=[authentication.validators.validate_image_extension]),
        ),
    ]
