# Generated by Django 3.1.4 on 2021-01-10 09:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20210109_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(db_index=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_title',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
    ]
