# Generated by Django 3.1.4 on 2021-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20210110_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_type',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ARABIC', 'ARABIC'), ('ENGLISH', 'ENGLISH')], default='ARABIC', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, choices=[('SAUDIARABIA', '+966'), ('JORDAN', '+962'), ('UNITEDARABEMIRATES', '+971'), ('BAHRAIN', '+973'), ('IRAQ', '+964')], default='SAUDIARABIA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Customer', 'Customer')], default='Developer', max_length=30),
        ),
    ]
