# Generated by Django 3.1.4 on 2021-01-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210120_2321'),
        ('authentication', '0018_auto_20210120_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
