# Generated by Django 3.1.4 on 2021-01-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_title',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
