# Generated by Django 3.1 on 2021-02-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='usersskill',
            old_name='user',
            new_name='owner',
        ),
    ]
